APPBUNDLE=${HOME}/Library/Developer/Xcode/DerivedData/HelloWorld-hfefmoxiegqtgqdbgrdrdfotdmbp/Build/Products/Debug-iphonesimulator

run:
	open -a Simulator --args -CurrentDeviceUDID  8EDC74C9-40CC-4C72-B926-F541FEC32CC3
	#/Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator -CurrentDeviceUDID 2B4C515C-159F-4116-BCEA-CA7A688EFC62
	xcrun simctl install 8EDC74C9-40CC-4C72-B926-F541FEC32CC3 ${APPBUNDLE}
	xcrun simctl launch 8EDC74C9-40CC-4C72-B926-F541FEC32CC3
