#!/usr/bin/env bash
# setup.sh — Install a per-user, sudo-free Jellyfin media server on
# Bazzite / Fedora Atomic (immutable) systems.
#
# Method: rootless Podman container defined by a Quadlet file
# (~/.config/containers/systemd/container-jellyfin.container) that systemd
# turns into a --user unit. No system packages, no root, no /usr overlays.
# Everything lives in your home directory; removing it means deleting the
# Quadlet file + data dir.
#
# Override any default via environment variables:
#   JF_PORT             HTTP port exposed on the host (default 8096)
#   JF_MEDIA_DIR        Host media directory (default /var/mnt/hdd/media)
#   JF_ADMIN_USER       Admin username created in first-run wizard (default admin)
#   JF_ADMIN_PASSWORD   Admin password (default: generated, saved to
#                       $JF_DATA_DIR/ADMIN_CREDENTIALS, mode 600)
#   JF_LIBRARY_NAME     Library display name (default Movies)
#   JF_IMAGE            Container image (default: pinned
#                       docker.io/jellyfin/jellyfin:10.11.11; override
#                       for a different tag/release)
#
# The script is idempotent: re-run it to repair or reconfigure.
set -euo pipefail

# --------------------------------------------------------------- defaults
JF_PORT="${JF_PORT:-8096}"
JF_MEDIA_DIR="${JF_MEDIA_DIR:-/var/mnt/hdd/media}"
JF_ADMIN_USER="${JF_ADMIN_USER:-admin}"
JF_ADMIN_PASSWORD="${JF_ADMIN_PASSWORD:-}"
JF_LIBRARY_NAME="${JF_LIBRARY_NAME:-Movies}"
JF_IMAGE="${JF_IMAGE:-docker.io/jellyfin/jellyfin:10.11.11}"
JF_LIBRARY_TYPE="${JF_LIBRARY_TYPE:-movies}"   # movies / tvshows / music / ...

JF_DATA_DIR="${JF_DATA_DIR:-$HOME/.local/share/jellyfin}"
B="http://127.0.0.1:${JF_PORT}"

# NOTE: on Bazzite / Silverblue-style systems /mnt is a symlink to
# /var/mnt, and rootless podman cannot bind-mount through it. Resolve
# the real path first. (Plain readlink -f would also follow this.)
JF_MEDIA_DIR=$(readlink -f "$JF_MEDIA_DIR")

die() { echo "SETUP FAILED: $*" >&2; exit 1; }
note() { printf '\n== %s\n' "$*"; }

command -v podman >/dev/null || die "podman not found (it ships with Bazzite)"
[ -d "$JF_MEDIA_DIR" ] || die "media dir '$JF_MEDIA_DIR' does not exist"

# --------------------------------------------------------------- state dir
note "Creating data dirs under $JF_DATA_DIR"
mkdir -p "$JF_DATA_DIR/config" "$JF_DATA_DIR/cache"

# --------------------------------------------------------------- quadlet unit
# The service is defined declaratively in a Quadlet file; systemd's podman
# user generator turns it into container-jellyfin.service on daemon-reload
# (no deprecation warning, readable source of truth). No container needs to
# exist beforehand — the generated unit rebuilds it on every start
# (self-healing), and `podman pull` + restart picks up image updates.
#
# SecurityLabelDisable=true: avoids SELinux relabeling of the
#   (possibly root-owned, shared) media directory. The mount is :ro.
JF_LEGACY_UNIT="$HOME/.config/systemd/user/container-jellyfin.service"
if [ -f "$JF_LEGACY_UNIT" ]; then
    note "Removing legacy generate-systemd unit (migrating to Quadlet)"
    systemctl --user disable --now container-jellyfin.service 2>/dev/null || true
    rm -f "$JF_LEGACY_UNIT" \
          "$HOME/.config/systemd/user/default.target.wants/container-jellyfin.service"
    # Wait out the old container's teardown so its published ports are
    # released before the Quadlet unit binds them (avoids a port race).
    for _ in $(seq 1 20); do
        podman container exists jellyfin 2>/dev/null || break
        sleep 1
    done
fi

note "Pulling image: $JF_IMAGE"
podman pull "$JF_IMAGE"

JF_QUADLET="$HOME/.config/containers/systemd/container-jellyfin.container"
note "Writing Quadlet unit: $JF_QUADLET"
mkdir -p "$(dirname "$JF_QUADLET")"
cat > "$JF_QUADLET" <<EOF
# Generated by jellyfin/setup.sh — edit setup.sh (or this file), then:
#   systemctl --user daemon-reload && systemctl --user restart container-jellyfin

[Unit]
Description=Jellyfin media server (rootless podman container)
Wants=network-online.target
After=network-online.target

[Container]
Image=${JF_IMAGE}
ContainerName=jellyfin
PublishPort=${JF_PORT}:8096
PublishPort=8920:8920
Volume=${JF_DATA_DIR}/config:/config
Volume=${JF_DATA_DIR}/cache:/cache
Volume=${JF_MEDIA_DIR}:/media:ro
SecurityLabelDisable=true
# Update policy for `podman auto-update` (driven by the daily
# podman-auto-update.timer). 'registry' compares the digest of the tag
# in Image= against the registry, so with a pinned release tag this is
# normally a no-op; it becomes live if Image= is ever changed to a
# mutable tag like :latest. NOTE: 'registry' requires a fully-qualified
# image name (registry/repo:tag).
AutoUpdate=registry

[Service]
Restart=on-failure
# Snapshot the config dir before every (re)start — precisely the moment
# an image change (manual re-pin or podman auto-update) takes effect.
# Jellyfin upgrades run DB schema migrations that do not reverse
# cleanly, so these snapshots are the downgrade safety net. Reflink
# copies are near-free on btrfs; keeps the last 6.
ExecStartPre=-/bin/sh -c 'S="%h/.local/share/jellyfin"; D="\$S/config-snapshots"; mkdir -p "\$D" && cp -a --reflink=auto "\$S/config" "\$D/config-\$(date +%%Y%%m%%d-%%H%%M%%S)" && ls -1dt "\$D"/config-* | tail -n +7 | xargs -r rm -rf'

[Install]
WantedBy=default.target
EOF

# Clear any stale container that would collide with the generated run
podman rm -f jellyfin 2>/dev/null || true
systemctl --user daemon-reload

# NOTE: generated units cannot be `systemctl enable`d ("transient or
# generated") — and don't need to be: the [Install] section above makes
# the podman user generator wire up default.target itself on every boot.
note "Starting service"
for _ in 1 2 3; do
    systemctl --user start container-jellyfin.service && break
    echo "start failed (port still releasing?); retrying in 3s" >&2
    sleep 3
done
systemctl --user is-active --quiet container-jellyfin.service \
    || die "container-jellyfin.service failed to start; check: journalctl --user -u container-jellyfin"

# Daily update *checks* (no-op while Image= is pinned to a release tag;
# see AutoUpdate= in the Quadlet file).
if systemctl --user list-unit-files podman-auto-update.timer --no-legend 2>/dev/null | grep -q '^podman-auto-update.timer'; then
    note "Enabling podman-auto-update.timer (daily update checks)"
    systemctl --user enable --now podman-auto-update.timer
else
    echo "NOTE: podman-auto-update.timer not found; skipping periodic update checks"
fi

# --------------------------------------------------------------- helper API functions
http_code() { curl -s -o /dev/null -w '%{http_code}' "$@"; }

api() { # api METHOD PATH [JSON_BODY] [TOKEN]
    local m=$1 p=$2 body=${3:-} token=${4:-}
    local args=(-s -X "$m" "$B$p" -H 'Content-Type: application/json')
    [ -n "$token" ] && args+=(-H "X-Emby-Token: $token")
    [ -n "$body" ] && args+=(-d "$body")
    curl "${args[@]}"
}

JF_AUTH='MediaBrowser Client="jellyfin-setup", Device="shell", DeviceId="jellyfin-setup", Version="1.0"'

wait_for_server() {
    note "Waiting for Jellyfin to come up on $B"
    for _ in $(seq 1 60); do
        [ "$(http_code "$B/System/Info/Public")" = 200 ] && return 0
        sleep 2
    done
    die "server did not come up; check: journalctl --user -u container-jellyfin"
}

# --------------------------------------------------------------- start server
wait_for_server

# --------------------------------------------------------------- admin credentials
if [ -z "$JF_ADMIN_PASSWORD" ]; then
    # reuse a previously saved password (idempotent re-runs)
    if [ -f "$JF_DATA_DIR/ADMIN_CREDENTIALS" ]; then
        JF_ADMIN_PASSWORD=$(sed -n 2p "$JF_DATA_DIR/ADMIN_CREDENTIALS")
    else
        JF_ADMIN_PASSWORD=$(head -c 12 /dev/urandom | base64 | tr -d '/+=' | head -c 16)
    fi
fi
printf '%s\n%s\n' "$JF_ADMIN_USER" "$JF_ADMIN_PASSWORD" > "$JF_DATA_DIR/ADMIN_CREDENTIALS"
chmod 600 "$JF_DATA_DIR/ADMIN_CREDENTIALS"

# --------------------------------------------------------------- first-run wizard
WIZARD=$(curl -s --max-time 10 "$B/System/Info/Public" | python3 -c 'import json,sys;print(json.load(sys.stdin).get("StartupWizardCompleted"))')
if [ "$WIZARD" != "True" ]; then
    note "Completing first-run wizard (creates admin user '$JF_ADMIN_USER')"
    # Order matters in Jellyfin 10.11: GET /Startup/User initializes the
    # pending wizard user (default name "root"); only then may you POST
    # your chosen name/password. POSTing first returns 404.
    # First boot also runs DB migrations - endpoints can be briefly
    # flaky, hence the retries.
    for _ in $(seq 1 30); do
        [ "$(http_code "$B/Startup/User")" = 200 ] && break
        sleep 2
    done
    # POST the admin credentials until it succeeds (204)
    for _ in $(seq 1 10); do
        [ "$(http_code -X POST "$B/Startup/User" -H 'Content-Type: application/json' \
            -d "{\"Name\":\"$JF_ADMIN_USER\",\"Password\":\"$JF_ADMIN_PASSWORD\"}")" = 204 ] && break
        sleep 2
    done
    # complete the wizard (204 on success), retrying transient failures
    for _ in $(seq 1 10); do
        if http_code -X POST "$B/Startup/Complete" | grep -q 204; then
            break
        fi
        sleep 2
    done
    # confirm the wizard actually completed
    [ "$(curl -s "$B/System/Info/Public" | python3 -c 'import json,sys;print(json.load(sys.stdin).get("StartupWizardCompleted"))')" = True ] \
        || die "wizard did not complete"
else
    note "Wizard already complete"
fi

# --------------------------------------------------------------- authenticate
# Note: the X-Emby-Authorization header is required by this endpoint
# even for the login request itself.
TOKEN=$(curl -s --max-time 10 -X POST "$B/Users/AuthenticateByName" \
    -H 'Content-Type: application/json' -H "X-Emby-Authorization: $JF_AUTH" \
    -d "{\"Username\":\"$JF_ADMIN_USER\",\"Pw\":\"$JF_ADMIN_PASSWORD\"}" \
    | python3 -c 'import json,sys;print(json.load(sys.stdin).get("AccessToken",""))' 2>/dev/null)
[ -n "$TOKEN" ] \
    || die "authentication failed for '$JF_ADMIN_USER' (wrong password? rerun with JF_ADMIN_PASSWORD=...)"
note "Authenticated as $JF_ADMIN_USER"

# --------------------------------------------------------------- remote access
# Enabled by default for LAN clients. Disable with JF_ALLOW_REMOTE=0.
if [ "${JF_ALLOW_REMOTE:-1}" = 1 ]; then
    note "Enabling remote access (LAN clients)"
    curl -s "$B/System/Configuration/network" -H "X-Emby-Token: $TOKEN" -o /tmp/jf-netcfg.json
    python3 -c '
import json
d = json.load(open("/tmp/jf-netcfg.json"))
d["EnableRemoteAccess"] = True
json.dump(d, open("/tmp/jf-netcfg-out.json", "w"))'
    curl -s -o /dev/null -X POST "$B/System/Configuration/network" \
        -H "X-Emby-Token: $TOKEN" -H 'Content-Type: application/json' \
        -d @/tmp/jf-netcfg-out.json
fi

# --------------------------------------------------------------- media library
LIBS=$(api GET /Library/VirtualFolders "" "$TOKEN")
EXISTS=$(echo "$LIBS" | python3 -c '
import json,sys
folders = json.load(sys.stdin)
print(any(f["Name"] == sys.argv[1] for f in folders))' "$JF_LIBRARY_NAME" 2>/dev/null || echo False)
if [ "$EXISTS" = "True" ]; then
    note "Library '$JF_LIBRARY_NAME' already exists"
else
    note "Creating library '$JF_LIBRARY_NAME' from $JF_MEDIA_DIR"
    # Paths inside the container are prefixed with /media (see volume mount).
    curl -s -o /dev/null -X POST \
        "$B/Library/VirtualFolders?name=${JF_LIBRARY_NAME}&collectionType=${JF_LIBRARY_TYPE}&refreshLibrary=false" \
        -H "X-Emby-Token: $TOKEN" -H 'Content-Type: application/json' \
        -d '{"LibraryOptions":{}}'
    curl -s -o /dev/null -X POST "$B/Library/VirtualFolders/Paths?refreshLibrary=false" \
        -H "X-Emby-Token: $TOKEN" -H 'Content-Type: application/json' \
        -d "{\"Name\":\"$JF_LIBRARY_NAME\",\"PathInfo\":{\"Path\":\"/media\"}}"
fi

note "Scanning library (this may take a while)"
curl -s -o /dev/null -X POST "$B/Library/Refresh" -H "X-Emby-Token: $TOKEN"

COUNT=0
for _ in $(seq 1 60); do
    sleep 5
    COUNT=$(api GET "/Items?recursive=true&fields=Path" "" "$TOKEN" \
        | python3 -c 'import json,sys;d=json.load(sys.stdin);print(d.get("TotalRecordCount",0))' 2>/dev/null || echo 0)
    [ "${COUNT:-0}" -gt 0 ] && break
done
note "Library scan finished: $COUNT item(s) indexed"

# --------------------------------------------------------------- linger (start at boot)
if ! loginctl show-user "$USER" -p Linger 2>/dev/null | grep -q '^Linger=yes'; then
    if loginctl enable-linger 2>/dev/null; then
        note "Linger enabled: services start at boot without login"
    else
        echo "NOTE: could not enable linger; server starts when you log in"
    fi
fi

# --------------------------------------------------------------- summary
LAN_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
cat <<EOF

================ Jellyfin setup complete ================
  Web UI (local):      http://127.0.0.1:${JF_PORT}
  Web UI (LAN):       http://${LAN_IP:-<lan-ip>}:${JF_PORT}
  Admin user:         $JF_ADMIN_USER
  Admin password:     in $JF_DATA_DIR/ADMIN_CREDENTIALS (mode 600)
  Media (read-only):  $JF_MEDIA_DIR -> /media in container
  Quadlet:            $JF_QUADLET
  Service:            systemctl --user status container-jellyfin

  Items indexed:      $COUNT

Caveats:
  - If LAN clients cannot connect, your distro firewall may block
    port ${JF_PORT}; on Bazzite check Firewall settings in the
    desktop settings panel (usually allowed for home LANs).
  - Auto-discovery (UDP 7359) is not proxied by rootless podman;
    add the server manually by IP in clients.
  - Media is mounted read-only; Jellyfin writes metadata/art to
    $JF_DATA_DIR/config instead.
=========================================================
EOF

# --------------------------------------------------------------- verify
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
[ -x "$SCRIPT_DIR/verify.sh" ] && "$SCRIPT_DIR/verify.sh"
