#!/bin/sh

if ! [ -f "$1-ready".wav ] ; then
	ffmpeg -t 15  -i "$1" -acodec pcm_s16le -ac 1 -ar 16000 "$1-ready".wav 
fi

FILE="$1"
shift

deepspeech --model deepspeech-0.6.0-models/output_graph.pbmm --lm deepspeech-0.6.0-models/lm.binary --trie deepspeech-0.6.0-models/trie --audio "$FILE-ready".wav "$@"

