app = "fly-debian-372"

[mounts]
  destination = "/work"
  source = "work"

# somehow this makes health checks pass (vs. "critical") even if nothing is listening
[[services]]
  internal_port = 22
  protocol = "tcp"
  [[services.ports]]
    port = 22
[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
      hard_limit = 25
      soft_limit = 20
      type = "connections"
  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
